/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as learnZodIndexRouteImport } from './routes/(learn)/zod/index'
import { Route as learnTypescriptIndexRouteImport } from './routes/(learn)/typescript/index'
import { Route as learnTransitionIndexRouteImport } from './routes/(learn)/transition/index'
import { Route as learnTableIndexRouteImport } from './routes/(learn)/table/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const learnZodIndexRoute = learnZodIndexRouteImport.update({
  id: '/(learn)/zod/',
  path: '/zod/',
  getParentRoute: () => rootRouteImport,
} as any)
const learnTypescriptIndexRoute = learnTypescriptIndexRouteImport.update({
  id: '/(learn)/typescript/',
  path: '/typescript/',
  getParentRoute: () => rootRouteImport,
} as any)
const learnTransitionIndexRoute = learnTransitionIndexRouteImport.update({
  id: '/(learn)/transition/',
  path: '/transition/',
  getParentRoute: () => rootRouteImport,
} as any)
const learnTableIndexRoute = learnTableIndexRouteImport.update({
  id: '/(learn)/table/',
  path: '/table/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/table': typeof learnTableIndexRoute
  '/transition': typeof learnTransitionIndexRoute
  '/typescript': typeof learnTypescriptIndexRoute
  '/zod': typeof learnZodIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/table': typeof learnTableIndexRoute
  '/transition': typeof learnTransitionIndexRoute
  '/typescript': typeof learnTypescriptIndexRoute
  '/zod': typeof learnZodIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/(learn)/table/': typeof learnTableIndexRoute
  '/(learn)/transition/': typeof learnTransitionIndexRoute
  '/(learn)/typescript/': typeof learnTypescriptIndexRoute
  '/(learn)/zod/': typeof learnZodIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/table'
    | '/transition'
    | '/typescript'
    | '/zod'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/table'
    | '/transition'
    | '/typescript'
    | '/zod'
  id:
    | '__root__'
    | '/'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/(learn)/table/'
    | '/(learn)/transition/'
    | '/(learn)/typescript/'
    | '/(learn)/zod/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  learnTableIndexRoute: typeof learnTableIndexRoute
  learnTransitionIndexRoute: typeof learnTransitionIndexRoute
  learnTypescriptIndexRoute: typeof learnTypescriptIndexRoute
  learnZodIndexRoute: typeof learnZodIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(learn)/zod/': {
      id: '/(learn)/zod/'
      path: '/zod'
      fullPath: '/zod'
      preLoaderRoute: typeof learnZodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(learn)/typescript/': {
      id: '/(learn)/typescript/'
      path: '/typescript'
      fullPath: '/typescript'
      preLoaderRoute: typeof learnTypescriptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(learn)/transition/': {
      id: '/(learn)/transition/'
      path: '/transition'
      fullPath: '/transition'
      preLoaderRoute: typeof learnTransitionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(learn)/table/': {
      id: '/(learn)/table/'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof learnTableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  learnTableIndexRoute: learnTableIndexRoute,
  learnTransitionIndexRoute: learnTransitionIndexRoute,
  learnTypescriptIndexRoute: learnTypescriptIndexRoute,
  learnZodIndexRoute: learnZodIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
